CREATE TABLE User
(
  UserID INT NOT NULL,
  Nickname VARCHAR(50) NOT NULL,
  Email VARCHAR(50) NOT NULL,
  Password VARCHAR(50) NOT NULL,
  PRIMARY KEY (UserID),
  UNIQUE (Nickname),
  UNIQUE (Email)
);

CREATE TABLE World
(
  W-Name VARCHAR(100) NOT NULL,
  W-ID INT NOT NULL,
  Lore VARCHAR(1000) NOT NULL,
  UserID INT NOT NULL,
  PRIMARY KEY (W-ID),
  FOREIGN KEY (UserID) REFERENCES User(UserID)
);

CREATE TABLE Item
(
  I-Name VARCHAR(500) NOT NULL,
  I-Details VARCHAR(1000),
  Item_notes VARCHAR(1000),
  I-ID INT NOT NULL,
  UserID INT NOT NULL,
  PRIMARY KEY (I-ID),
  FOREIGN KEY (UserID) REFERENCES User(UserID)
);

CREATE TABLE Entity
(
  E-Name VARCHAR(200) NOT NULL,
  E-Details VARCHAR(1000),
  Player_Notes VARCHAR(1000),
  E-ID INT NOT NULL,
  Type VARCHAR(200) NOT NULL,
  UserID INT NOT NULL,
  PRIMARY KEY (E-ID),
  FOREIGN KEY (UserID) REFERENCES User(UserID),
  UNIQUE (E-Name)
);

CREATE TABLE Location
(
  L-Name VARCHAR(500) NOT NULL,
  L-Description VARCHAR(1000) NOT NULL,
  L-ID INT NOT NULL,
  PRIMARY KEY (L-ID)
);

CREATE TABLE Campain
(
  Story VARCHAR(2000) NOT NULL,
  C-Name VARCHAR(100) NOT NULL,
  C-ID INT NOT NULL,
  W-ID INT NOT NULL,
  PRIMARY KEY (C-ID),
  FOREIGN KEY (W-ID) REFERENCES World(W-ID)
);

CREATE TABLE Stat
(
  S-Name VARCHAR(100) NOT NULL,
  S-Value INT NOT NULL,
  I-ID INT NOT NULL,
  E-ID INT NOT NULL,
  PRIMARY KEY (S-Name),
  FOREIGN KEY (I-ID) REFERENCES Item(I-ID),
  FOREIGN KEY (E-ID) REFERENCES Entity(E-ID)
);

CREATE TABLE Action/Ability
(
  A-Name INT NOT NULL,
  A-Value INT NOT NULL,
  PRIMARY KEY (A-Name)
);

CREATE TABLE is_in
(
  C-ID INT NOT NULL,
  L-ID INT NOT NULL,
  PRIMARY KEY (C-ID, L-ID),
  FOREIGN KEY (C-ID) REFERENCES Campain(C-ID),
  FOREIGN KEY (L-ID) REFERENCES Location(L-ID)
);

CREATE TABLE is_found_in
(
  C-ID INT NOT NULL,
  I-ID INT NOT NULL,
  PRIMARY KEY (C-ID, I-ID),
  FOREIGN KEY (C-ID) REFERENCES Campain(C-ID),
  FOREIGN KEY (I-ID) REFERENCES Item(I-ID)
);

CREATE TABLE plays_in
(
  C-ID INT NOT NULL,
  E-ID INT NOT NULL,
  PRIMARY KEY (C-ID, E-ID),
  FOREIGN KEY (C-ID) REFERENCES Campain(C-ID),
  FOREIGN KEY (E-ID) REFERENCES Entity(E-ID)
);

CREATE TABLE owns
(
  E-ID INT NOT NULL,
  I-ID INT NOT NULL,
  PRIMARY KEY (E-ID, I-ID),
  FOREIGN KEY (E-ID) REFERENCES Entity(E-ID),
  FOREIGN KEY (I-ID) REFERENCES Item(I-ID)
);

CREATE TABLE can_perform
(
  A-Name INT NOT NULL,
  I-ID INT NOT NULL,
  PRIMARY KEY (A-Name, I-ID),
  FOREIGN KEY (A-Name) REFERENCES Action/Ability(A-Name),
  FOREIGN KEY (I-ID) REFERENCES Item(I-ID)
);

CREATE TABLE can_do
(
  E-ID INT NOT NULL,
  A-Name INT NOT NULL,
  PRIMARY KEY (E-ID, A-Name),
  FOREIGN KEY (E-ID) REFERENCES Entity(E-ID),
  FOREIGN KEY (A-Name) REFERENCES Action/Ability(A-Name)
);

CREATE TABLE Scenario
(
  S-Name VARCHAR(100) NOT NULL,
  S-ID INT NOT NULL,
  UserID INT NOT NULL,
  L-ID INT NOT NULL,
  PRIMARY KEY (S-ID),
  FOREIGN KEY (UserID) REFERENCES User(UserID),
  FOREIGN KEY (L-ID) REFERENCES Location(L-ID)
);

CREATE TABLE exists
(
  E-ID INT NOT NULL,
  S-ID INT NOT NULL,
  PRIMARY KEY (E-ID, S-ID),
  FOREIGN KEY (E-ID) REFERENCES Entity(E-ID),
  FOREIGN KEY (S-ID) REFERENCES Scenario(S-ID)
);