CREATE TABLE User
(
  UserID INT NOT NULL AUTO_INCREMENT,
  Nickname VARCHAR(50) NOT NULL,
  Email VARCHAR(50) NOT NULL,
  Password VARCHAR(50) NOT NULL,
  PRIMARY KEY (UserID),
  UNIQUE (Nickname),
  UNIQUE (Email)
);

CREATE TABLE World
(
  W_Name VARCHAR(100) NOT NULL,
  W_ID INT NOT NULL AUTO_INCREMENT,
  Lore VARCHAR(1000) NOT NULL,
  UserID INT NOT NULL,
  PRIMARY KEY (W_ID),
  FOREIGN KEY (UserID) REFERENCES User(UserID)
);

CREATE TABLE Item
(
  I_Name VARCHAR(500) NOT NULL,
  I_Details VARCHAR(1000),
  Item_notes VARCHAR(1000),
  I_ID INT NOT NULL AUTO_INCREMENT,
  UserID INT NOT NULL,
  PRIMARY KEY (I_ID),
  FOREIGN KEY (UserID) REFERENCES User(UserID)
);

CREATE TABLE Entity
(
  E_Name VARCHAR(200) NOT NULL,
  E_Details VARCHAR(1000),
  Player_Notes VARCHAR(1000),
  E_ID INT NOT NULL AUTO_INCREMENT,
  Type VARCHAR(200) NOT NULL,
  UserID INT NOT NULL,
  PRIMARY KEY (E_ID),
  FOREIGN KEY (UserID) REFERENCES User(UserID),
  UNIQUE (E_Name)
);

CREATE TABLE Location
(
  L_Name VARCHAR(500) NOT NULL,
  L_Description VARCHAR(1000) NOT NULL,
  L_ID INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (L_ID)
);

CREATE TABLE Campain
(
  Story VARCHAR(2000) NOT NULL,
  C_Name VARCHAR(100) NOT NULL,
  C_ID INT NOT NULL AUTO_INCREMENT,
  W_ID INT NOT NULL,
  PRIMARY KEY (C_ID),
  FOREIGN KEY (W_ID) REFERENCES World(W_ID)
);

CREATE TABLE Stat
(
  S_Name VARCHAR(100) NOT NULL,
  S_Value INT UNSIGNED NOT NULL,
  I_ID INT NOT NULL,
  E_ID INT NOT NULL,
  PRIMARY KEY (S_Name),
  FOREIGN KEY (I_ID) REFERENCES Item(I_ID),
  FOREIGN KEY (E_ID) REFERENCES Entity(E_ID)
);

CREATE TABLE Action_Ability
(
  A_ID INT NOT NULL,
  A_Name VARCHAR(100) NOT NULL,
  A_Description VARCHAR(1000) NOT NULL,
  PRIMARY KEY (A_Name)
);

CREATE TABLE is_in
(
  C_ID INT NOT NULL,
  L_ID INT NOT NULL,
  PRIMARY KEY (C_ID, L_ID),
  FOREIGN KEY (C_ID) REFERENCES Campain(C_ID),
  FOREIGN KEY (L_ID) REFERENCES Location(L_ID)
);

CREATE TABLE is_found_in
(
  C_ID INT NOT NULL,
  I_ID INT NOT NULL,
  PRIMARY KEY (C_ID, I_ID),
  FOREIGN KEY (C_ID) REFERENCES Campain(C_ID),
  FOREIGN KEY (I_ID) REFERENCES Item(I_ID)
);

CREATE TABLE plays_in
(
  C_ID INT NOT NULL,
  E_ID INT NOT NULL,
  PRIMARY KEY (C_ID, E_ID),
  FOREIGN KEY (C_ID) REFERENCES Campain(C_ID),
  FOREIGN KEY (E_ID) REFERENCES Entity(E_ID)
);

CREATE TABLE owns
(
  E_ID INT NOT NULL,
  I_ID INT NOT NULL,
  PRIMARY KEY (E_ID, I_ID),
  FOREIGN KEY (E_ID) REFERENCES Entity(E_ID),
  FOREIGN KEY (I_ID) REFERENCES Item(I_ID)
);

CREATE TABLE can_perform
(
  A_Name INT NOT NULL,
  I_ID INT NOT NULL,
  PRIMARY KEY (A_Name, I_ID),
  FOREIGN KEY (A_Name) REFERENCES Action/Ability(A_Name),
  FOREIGN KEY (I_ID) REFERENCES Item(I_ID)
);

CREATE TABLE can_do
(
  E_ID INT NOT NULL,
  A_Name INT NOT NULL,
  PRIMARY KEY (E_ID, A_Name),
  FOREIGN KEY (E_ID) REFERENCES Entity(E_ID),
  FOREIGN KEY (A_Name) REFERENCES Action/Ability(A_Name)
);

CREATE TABLE Scenario
(
  S_Name VARCHAR(100) NOT NULL,
  S_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  UserID INT NOT NULL,
  L_ID INT NOT NULL,
  PRIMARY KEY (S_ID),
  FOREIGN KEY (UserID) REFERENCES User(UserID),
  FOREIGN KEY (L_ID) REFERENCES Location(L_ID)
);

CREATE TABLE existsin
(
  E_ID INT NOT NULL,
  S_ID INT NOT NULL,
  PRIMARY KEY (E_ID, S_ID),
  FOREIGN KEY (E_ID) REFERENCES Entity(E_ID),
  FOREIGN KEY (S_ID) REFERENCES Scenario(S_ID)
);
